User edit entries
samlee0258/code-journal pull request #7
Opened 2023-01-11 19:51 UTC by samlee0258

https://user-images.githubusercontent.com/110208589/211904089-16f67a7e-2366-4cd8-8dae-cd1efeea169c.mp4

2023-01-11 19:54 UTC, codingcodymiller requested changes

2023-01-11 19:54 UTC, codingcodymiller commented on js/main.js
> +};
This should not be global, it should be in your `submit` event handler function

2023-01-11 19:54 UTC, codingcodymiller commented on js/main.js
> +  location.reload();
_**NOOOOOO**_ 💀 

This reloads your page entirely, which is the worst possible action you can take. Why are you doing this? 😭

2023-01-11 20:01 UTC, samlee0258 commented on js/main.js
> +};
<img width="647" alt="Screenshot 2023-01-11 at 11 58 57 AM" src="https://user-images.githubusercontent.com/110208589/211906064-f9041efd-5cff-4ed5-8adf-5607b5aab980.png">

2023-01-11 20:01 UTC, samlee0258 commented on js/main.js
> +};
removed!

2023-01-11 20:01 UTC, samlee0258 commented on js/main.js
> +  location.reload();
<img width="321" alt="Screenshot 2023-01-11 at 11 58 46 AM" src="https://user-images.githubusercontent.com/110208589/211906133-fbea39d6-a654-4c28-b642-4ad5a637c2fd.png">

2023-01-11 20:02 UTC, samlee0258 commented on js/main.js
> +  location.reload();
removed! my bad i added it in so that when the submit went through it would refresh the page so i could see the entry addition or edit without manually refreshing the page to see the changes.

2023-01-11 20:03 UTC, samlee0258 commented on js/main.js
> +  location.reload();
didnt know it was bad

2023-01-12 17:16 UTC, codingcodymiller approved these changes

2023-01-12 17:21 UTC, merged